### PR TITLE
 Add AzureFS addon for jmix version 2.2.x 

### PR DESCRIPTION
**Pull request by pbaris**
Add AzureFS and AzureFS starter dependencies to bom.gradle

### CODE REVIEW

**Comment by knstvk** [comment]
Hi Panos
As I understand, `gr.netmechanics.jmix:azurefs:2.1.0` depends on Jmix 2.1.
We expect that you build a separate version of the add-on based on Jmix 2.2. Could you do it?

**Comment by pbaris** [comment]
Hi Konstantin

What i do not get with 2.x.x, is how i will build my addon for the next version (e.g. 2.2.x) when Jmix studio supports, till the current released version?

image

If i am not wrong in 1.5.x versions, first there was a studio update, then i build my addon with this version, then i was made the PR, and finally jmix framework was release (i don't remember the process exactly).

Beyond that gr.netmechanics.jmix:azurefs:2.1.0 is build with jmix studio 2.1.3

**Comment by pbaris** [comment]
i build the addon with jmix 2.2.0-RC1

**Comment by knstvk** [comment]
Thanks!

**Pull request merged**
